version: '2'
services:
    db:
        image: mongo:3.2
        restart: always
    web:
        depends_on:
            - db
        links:
            - db:docker-mongo-db
        image: docker-workshop-todo
        volumes:
            - "/home/docker_u/Desktop/workshop3/docker-workshop-todo/:/app"
        working_dir: /app
        restart: always
        
        ports:
            - "5000:5000"
        command: python app.py